# Generated by Django 4.2.1 on 2023-06-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('created_at',)},
        ),
    ]
