# Generated by Django 4.2.1 on 2023-06-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
