# Generated by Django 4.2.1 on 2023-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
