# Generated by Django 4.2.1 on 2023-06-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_remove_tweet_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
